### Post 135
**Post URL**: /t/tds-official-project1-discrepencies/171141/135
- **ID**: 613804
- **Author**: K Senthur Kumaran  (22f3002902)
- **Created At**: 2025-03-31T09:29:51.137Z
- **Content**:  
  Hello sir
I noticed that the log mentioned:<br>
“python: can’t open file ‘/app/app/main.py’: [Errno 2] No such file or directory.”
However, my main file was named run.py, which might have caused the issue. Since the code was present, I was given a 0. Would it be possible to run it again or consider partial marks for the submission?
Thank you for your time and consideration. I appreciate your help!
- **Reactions**: None
- **Post Number**: 135

