### Post 538
**Post URL**: /t/project-1-llm-based-automation-agent-discussion-thread-tds-jan-2025/164277/538
- **ID**: 595955
- **Author**: Aishik Bandyopadhyay (23f2005325)
- **Created At**: 2025-02-16T13:11:13.013Z
- **Reply To**: Post 537 (J Rohan Atre , 23f1000371)
- **Content**:  
  I am getting this error while running evaluate.py on task A9
<pre data-code-wrap="bash"><code class="lang-bash">HTTP Request: POST https://aiproxy.sanand.workers.dev/openai/v1/embeddings "HTTP/1.1 401 Unauthorized"

ðŸ”´ A9 failed: 'data'
</code></pre>
There were no authentication issues till yesterday.
please guide <a class="mention" href="/u/carlton">@carlton</a> <a class="mention" href="/u/jivraj">@Jivraj</a> <a class="mention" href="/u/saransh_saini">@Saransh_Saini</a>
- **Reactions**: heart (1)
- **Post Number**: 538

